version: '3'

services:
  web:
    build: .
    ports:
      - "8083:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: reportdb
      MYSQL_USER: reportuser
      MYSQL_PASSWORD: reportpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

