version: '3'

services:
  web:
    build: .
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - vulnnet

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vulnlogin
      MYSQL_USER: vuln
      MYSQL_PASSWORD: vulnpass
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - vulnnet

networks:
  vulnnet:

